require 'huginn_agent'

HuginnAgent.load 'huginn_acumen_product_agent/concerns/acumen_query_concern'
HuginnAgent.load 'huginn_acumen_product_agent/concerns/alternate_products_query_concern'
HuginnAgent.load 'huginn_acumen_product_agent/concerns/inv_product_query_concern'
HuginnAgent.load 'huginn_acumen_product_agent/concerns/inv_status_query_concern'
HuginnAgent.load 'huginn_acumen_product_agent/concerns/prod_mkt_query_concern'
HuginnAgent.load 'huginn_acumen_product_agent/concerns/product_categories_query_concern'
HuginnAgent.load 'huginn_acumen_product_agent/concerns/product_contributors_query_concern'

HuginnAgent.load 'huginn_acumen_product_agent/acumen_client'
HuginnAgent.load 'huginn_acumen_product_agent/acumen_agent_error'

HuginnAgent.register 'huginn_acumen_product_agent/acumen_product_agent'
